### ISSUE TITLE
Add deserialization support for `Table<R, C, V>`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-datatypes-collections#1]
(note: moved from https://github.com/FasterXML/jackson-datatype-guava/issues/11)

The Guava [`Table<R, C, V>`](http://docs.guava-libraries.googlecode.com/git-history/v13.0/javadoc/com/google/common/collect/Table.html) data structure is a convenience wrapper around a `Map<R, Map<C, V>>`.  This form can be easily serialized and deserialized.  Here's the basic code I'm using for that:

``` java
    public static class TableSerializer extends JsonSerializer<Table<?, ?, ?>> {
        @Override
        public void serialize(final Table<?, ?, ?> value, final JsonGenerator jgen, final SerializerProvider provider) throws IOException,
                    JsonProcessingException {
            jgen.writeObject(value.rowMap());
        }


        @Override
        public Class<Table<?, ?, ?>> handledType() {
            return (Class)Table.class;
        }
    } // end class TableSerializer

    public static class TableDeserializer extends JsonDeserializer<Table<?, ?, ?>> {
        @Override
        public Table<?, ?, ?> deserialize(final JsonParser jp, final DeserializationContext ctxt) throws IOException, JsonProcessingException {
            final ImmutableTable.Builder<Object, Object, Object> tableBuilder = ImmutableTable.builder();
            final Map<Object, Map<Object, Object>> rowMap = jp.readValueAs(Map.class);
            for (final Map.Entry<Object, Map<Object, Object>> rowEntry : rowMap.entrySet()) {
                final Object rowKey = rowEntry.getKey();
                for (final Map.Entry<Object, Object> cellEntry : rowEntry.getValue().entrySet()) {
                    final Object colKey = cellEntry.getKey();
                    final Object val = cellEntry.getValue();
                    tableBuilder.put(rowKey, colKey, val);
                }
            }
            return tableBuilder.build();
        }
    } // end class TableDeserializer

```

I have not tested if this correctly supports contextual keys or type (de)serialization.  I looked at `MultimapSerializer` and `MultimapDeserializer`, and they are much more complicated even though a `Multimap<K, V>` is just a convenience wrapper around `Map<K, Collection<V>>`, so maybe this is too simplistic?

Notably, this implementation always deserializes to an [`ImmutableTable`](http://docs.guava-libraries.googlecode.com/git-history/v13.0/javadoc/com/google/common/collect/ImmutableTable.html).  Heuristics could be used to determine what `Table` implementation to reconstruct, e.g., if every row, column value is non-null, could create [`ArrayTable`](http://docs.guava-libraries.googlecode.com/git-history/v13.0/javadoc/com/google/common/collect/ArrayTable.html).  [`HashBasedTable`](http://docs.guava-libraries.googlecode.com/git-history/v13.0/javadoc/com/google/common/collect/HashBasedTable.html) would be a good mutable default.

**Comment by cowtowncoder** [comment]
Note: existing PRs from the old project:

* https://github.com/FasterXML/jackson-datatype-guava/pull/62
* https://github.com/FasterXML/jackson-datatype-guava/pull/73

**Comment by cowtowncoder** [comment]
Also note that Jackson 2.7 has serialization support, but NOT yet deserialization -- this is why issue is still open.

**Comment by cowtowncoder** [comment]
@michaelhixson  @hyandell just FYI that Guava has moved; still hoping to eventually get to support Tables fully, but haven't had time to work on merging any further.

**Comment by lrlinde** [comment]
@cowtowncoder, I asked here
https://github.com/FasterXML/jackson-datatype-guava/issues/11
But I see this was duplicating it, so I'll ask here! :p

Is there any news on this? We'll working around this issue in our project and really appreciate fully support for Tables.

**Comment by cowtowncoder** [comment]
@lrlinde at this point I would need a new PR for this project for deserialization support. I don't have time to work on this myself.
