### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [FasterXML/jackson-datatypes-collections#10]
Hi

All java source files are without license headers.

Please, confirm the licensing of code and/or content/s, and add license headers

https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

This is currently blocking the import of these libraries in Fedora [1]

Thanks in advance

Regards

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1369232

**Comment by cowtowncoder** [comment]
@puntogil This is not a Fedora project, and our policy is not to add license boilerplate in source files.
It serves no useful purpose to us, so we have no intention of adding such headers.

License information is however included in Maven definitions (parent `pom.xml`), source repositories, and artifacts (via `src/main/resources`). Git repo wikis also include license information.

**Comment by puntogil** [comment]
hi
yes I know. but if i want to import one of your libraries in Fedora
then i must follow the Fedora packaging guidelines.
When happen this kind of problems i am obliged to report it
otherwise the "review" to import the package stops.
https://bugzilla.redhat.com/show_bug.cgi?id=1369232

Again thanks
Regards

**Comment by cowtowncoder** [comment]
Ok. Thank you for the explanation!

**Comment by puntogil** [comment]
hi
I created this license header, for those files where missing:
```
 /* 
 * Copyright (c) FasterXML, LLC.
 * Licensed to the Apache Software Foundation (ASF) 
 * under one or more contributor license agreements;
 * and to You under the Apache License, Version 2.0. 
 */
```
you can add it? or is still a question of minimizing the
weight of your libraries in Android environment?
if I have understood well the last time we came on this topic
If you lack the time to do it, i could create a PR, even for https://github.com/FasterXML/jackson-modules-base/issues/18
Again thanks
Regards

**Comment by puntogil** [comment]
http://www.apache.org/legal/src-headers.html
