### ISSUE TITLE
ImmutableRangeSet fails to deserialize without explicit deserializer

### ISSUE THREAD

**Issue by chris-dekker** [FasterXML/jackson-datatypes-collections#117]
Any concrete `ImmutableRangeSet<T>` type fails to deserialize out of the box using the `GuavaDeserializers`.

Only when explicitly setting `@JsonDeserialize(using = RangeSetDeserializer.class)` on the field does it work correctly. 

Problem seems to be in the [GuavaDeserializers.java](https://github.com/FasterXML/jackson-datatypes-collections/blob/2.16/guava/src/main/java/com/fasterxml/jackson/datatype/guava/GuavaDeserializers.java#L320-L322). This should check for `RangeSet.class.isAssignableFrom(type.getRawClass())` instead :crossed_fingers:

**Comment by cowtowncoder** [comment]
Thank you for reporting this @chris-dekker. But just to make sure, could you show usage? Is the target type `ImmutableRangeSet`?

If annotation works, fix might be relatively simple.

cc @JooHyukKim
