### ISSUE TITLE
`Range` deserialization fails when `ObjectMapper` has default typing enabled

### ISSUE THREAD

**Issue by kringol** [FasterXML/jackson-datatypes-collections#12]
If i have an ObjectMapper like the following

```
final ObjectMapper mapper = new ObjectMapper();
mapper.registerModule(new GuavaModule());
mapper.setDefaultTyping(new ObjectMapper.DefaultTypeResolverBuilder(ObjectMapper.DefaultTyping.NON_FINAL));
```

And then I try to serialize a Guava Range into an String, it becomes
```
{
        "lowerEndpoint": 1,
        "lowerBoundType": [
          "com.google.common.collect.BoundType",
          "CLOSED"
        ],
        "upperEndpoint": 10,
        "upperBoundType": [
          "com.google.common.collect.BoundType",
          "CLOSED"
        ]
}
```
Instead of the basic
```
    {
      "lowerEndpoint": 1,
      "lowerBoundType": "CLOSED",
      "upperEndpoint": 10,
      "upperBoundType": "CLOSED"
    }
```

So far, so good
But if you try to deserialized that first json. 
The Range Deserializer throws an error
```
com.fasterxml.jackson.databind.JsonMappingException: Expecting VALUE_STRING, found START_ARRAY
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.datatype.guava.deser.RangeDeserializer.expect(RangeDeserializer.java:194)
	at com.fasterxml.jackson.datatype.guava.deser.RangeDeserializer.deserializeBoundType(RangeDeserializer.java:171)
```
Seems that this check
https://github.com/FasterXML/jackson-datatypes-collections/blob/master/guava/src/main/java/com/fasterxml/jackson/datatype/guava/deser/RangeDeserializer.java#L175
Doesn't work very happily with ObjectMappers using "Typers"

Not entirely sure where to fix this or how to avoid this

Regarding using Typers on the mapper, it's begin used by a popular redis client lib
https://github.com/redisson/redisson

Thanks

**Comment by cowtowncoder** [comment]
Most likely `RangeSerializer` is using delegation for `BoundType` but really shouldn't; but then deserializer is not delegating handling. I haven't looked at code but I suspect something like this is going on: I don't think polymorphic typing should be enabled for those properties.

**Comment by cowtowncoder** [comment]
Ok yes; so, whereas "endpoint"s are symmetrically delegated, bound types are not: on serialization they are handled using:

    provider.defaultSerializeField(...)

but deserializer simply expects to get a (JSON) String to map.
Given that `BoundType` is an enum it probably should just be serialized using `name()`; probably no reason to make it be configured as regular enum (which can be configured to use alternative representations).
