### ISSUE TITLE
PCollections module info (`module-info.class`) incorrect

### ISSUE THREAD

**Issue by bowbahdoe** [FasterXML/jackson-datatypes-collections#122]
```xml
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-pcollections</artifactId>
            <version>2.15.3</version>
        </dependency>

        <dependency>
            <groupId>org.pcollections</groupId>
            <artifactId>pcollections</artifactId>
            <version>4.0.1</version>
        </dependency>
 ```
 
 ```
 Error occurred during initialization of boot layer
java.lang.module.FindException: Module pcollections not found, required by jackson.datatype.pcollections
```

Their module name is now `org.pcollections` https://github.com/hrldcpr/pcollections/blob/master/src/main/java/module-info.java

**Comment by cowtowncoder** [comment]
Thank you for reporting this @bowbahdoe. Sounds like something to fix in config file for Moditect.

**Comment by bowbahdoe** [comment]
@cowtowncoder You fixed that without bumping the minimum version of pcollections. This was an error encountered with 4.x.y, I don't know if it was an issue with 2.x.y

**Comment by cowtowncoder** [comment]
Ugh. Was too hasty, assumed it was a problem you had encountered and... crap. 

Thank you for pointing this out; will change.

**Comment by cowtowncoder** [comment]
Updated for 2.16.0. For 2.15.x bit unclear on what to do since as far as I can see, module-info is only added in PCollections 4.0.1 -- so there is no module name for prior versions. But also not sure how safe it'd be to upgrade PCollections dependency from 2.x to 4.x in a patch (of 2.15).
