### ISSUE TITLE
[hppc] @JsonDeserialize contentAs support is wanted

### ISSUE THREAD

**Issue by plokhotnyuk** [FasterXML/jackson-datatypes-collections#16]
...to allow parsing array of numbers represented by strings and bind them to IntHashSet, etc.

**Comment by cowtowncoder** [comment]
Do you mean that values are Strings containing numbers?

It might be easiest to show bit of code (or even unit test?) to make sure I understand the intent.

Note, too, that specific mechanism of `contentAs` must conform to Java type (NOT json representation), so, for example `IntHashSet` really would not benefit from this. However it should support coercion from Strings, if allowed by relevant `DeserializationFeature`s (there is something about forcing strict numbers).

**Comment by cowtowncoder** [comment]
And to clarify wrt above: I think what is wanted is value coercions, which is fine; and with 2.12 there is new `CoercionConfig` to verify that such action is allowed by user.

**Comment by plokhotnyuk** [comment]
Sorry, it was 3 years ago... Now I don't remember a context. Probably it was solved by some custom serializer and deserializer.

**Comment by cowtowncoder** [comment]
@plokhotnyuk ok np.
