### ISSUE TITLE
(guava) Multimap serializer produces wrong Schema structure

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-datatypes-collections#19]
(note: root cause for https://github.com/FasterXML/jackson-dataformats-binary/issues/103)

Looks like `MultimapSerializer` is reporting its structure same as regular `MapSerializer`.
This incorrect since its values are wrapped in an array.

**Comment by wbautistaEXPEDIA** [comment]
Thanks a ton for getting to this so quickly. Do you have an ETA on the release for this? Also, please confirm this will be available in 2.9.1.

**Comment by cowtowncoder** [comment]
Yes, this will be in 2.9.1. Releases usually based on rate of fixes (released when enough important fixes).
Usually first .1 release occurs no later than 4 weeks after .0 release, but there's been surprisingly low rate of bug reports so we'll see. Guessing end of August 2017 might be likely release date.

**Comment by wbautistaEXPEDIA** [comment]
I noticed the 2.8 line was released. Any update on 2.9.1?

**Comment by cowtowncoder** [comment]
@wbautistaEXPEDIA Still collecting patches, but should do release within next 2 weeks.
