### ISSUE TITLE
guava tests failing with jdk8

### ISSUE THREAD

**Issue by ernesto-alvarado** [FasterXML/jackson-datatypes-collections#47]
The test jackson-datatypes-collections/guava/src/test/java/com/fasterxml/jackson/datatype/guava/TestMultimaps.java fails with:

```
jackson-datatypes-collections/guava/src/test/java/com/fasterxml/jackson/datatype/guava/TestMultimaps.java:[134,37] no suitable method found for readValue(java.lang.String,<anonymous com.fas
terxml.jackson.core.type.TypeReference<com.google.common.collect.TreeMultimap<java.lang.String,java.lang.Boolean>>>)
```

Is this test outdated?

**Comment by cowtowncoder** [comment]
No, this should work just fine, but it is probably compilation issue wrt 3.0 refactoring that I just fixed yesterday.
