### ISSUE TITLE
`GuavaImmutableCollectionDeserializer` cannot deserialize an empty `Optional` from null

### ISSUE THREAD

**Issue by jonfreedman** [FasterXML/jackson-datatypes-collections#53]
The following test should pass

```java
public void testImmutableListOfOptionals() throws IOException {
	ImmutableList<OptionalInt> list = MAPPER.readValue("[1,null,3]", new TypeReference<ImmutableList<OptionalInt>>() { });
	assertEquals(3, list.size());
	assertEquals(OptionalInt.of(1), list.get(0));
	assertEquals(OptionalInt.empty(), list.get(1));
	assertEquals(OptionalInt.of(3), list.get(2));
}
```
See https://github.com/FasterXML/jackson-datatypes-collections/issues/27

**Comment by cowtowncoder** [comment]
I assume this is verified against 2.9.9?

**Comment by jonfreedman** [comment]
I've verified against 2.9.6 but I checked your source, you need to change this line: https://github.com/FasterXML/jackson-datatypes-collections/blob/master/guava/src/main/java/com/fasterxml/jackson/datatype/guava/deser/GuavaImmutableCollectionDeserializer.java#L40

value = null;
becomes
value = valueDes.getNullValue(ctxt);

Same fix as https://github.com/FasterXML/jackson-datatypes-collections/commit/0fc5e8baa639b3a70f98f34633864f8cc8688d6d#diff-3e1e6a8832674f14bb424827a0180c66L157

**Comment by cowtowncoder** [comment]
Got it, thanks!

**Comment by cowtowncoder** [comment]
I think this is now fixed, although for testing need to use `AtomicReference` for validation as I can not add dependency to JDK8 module to use Java 8 Optional types.

**Comment by jonfreedman** [comment]
Thanks, I'll verify when you cut the next release
