### ISSUE TITLE
Unreliable test for `eclipse collections`: `DeserializerTest.pairTyped()` sometimes fails

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-datatypes-collections#54]
So, not sure if this is something I have caused, but one test in `DeserializerTest` seems to occasional fail (on JDK 8 at lest), as serialization order of `one` and `two` sometimes change.
I didn't dig deep, but maybe it is just that `ObjectXxxPair` entries are serialized as POJOs in which case order is arbitrary (and so test should be made more robust not to assume ordering).

If so, one thing that would be nice, if practical, would be to register explicit serializer that would serialize entries in order: partly for more stable output, but partly since it could be made more efficient (direct accessors, writes). If so, test could remain as is.
But I don't know if writing such serializer is practical if all types are generated: probably depends on how practical it'd be to auto-generate serializers.

**Comment by cowtowncoder** [comment]
Forgot to mention: this occurs in `2.10` branch (haven't checked earlier).

**Comment by cowtowncoder** [comment]
@yawkat WDYT?

**Comment by yawkat** [comment]
This is the same issue as #52 

You are right about the cause. At this point I'd rather avoid adding a special serializer for pairs, at least until the fastutil work is complete. I will make a PR to make the test more robust for now
