### ISSUE TITLE
A shared utility to test collection types

### ISSUE THREAD

**Issue by leventov** [FasterXML/jackson-datatypes-collections#63]
It would be nice if there was a shared utility to test the dark corners of ser/deser implementation for proper collection types (i. e. extending either `Collection` or `Map`):
 - Tricky (perhaps, recursive) TypeReferences as contained types
 - Contained types specified in a non-standard way, e. g. via annotation
 - Heterogeneous values
 - Raw collection serialization / deserialization (no generics)

The idea is to actually put the logic of `ContainerSerializer` under test.

This common utility could be reused for testing core JDK Map/List/Set serializers/deserializers, as well as Guava collections, Eclipse Collections' reference collections, and fastutil's Object collections.

**Comment by cowtowncoder** [comment]
That would be nice: perhaps something similar to `jackson-compat-minor` project which tried to offer simple verification of compatibility (or lack thereof) between "close enough" minor versions (like datatypes 2.9 working against databind 2.8)

**Comment by cowtowncoder** [comment]
No current plans for further work, closing. Can be re-opened/re-filed if this becomes actual again.
