### ISSUE TITLE
LICENSE file in .jar

### ISSUE THREAD

**Issue by ajorg-aws** [FasterXML/jackson-datatypes-collections#81]
Hello, We've seen a problem a few times where our systems are unable to detect the LICENSE file in the .jar files for these packages because instead of actually containing the Apache-2.0 license file and a separate NOTICE file it contains only the following, which our tools aren't able to parse (without extra code, which we're also working on).

```
This copy of Jackson JSON processor streaming parser/generator is licensed under the
Apache (Software) License, version 2.0 ("the License").
See the License for details about distribution rights, and the
specific rights regarding derivate works.

You may obtain a copy of the License at:

http://www.apache.org/licenses/LICENSE-2.0
```

I wondered if your customers would be better served by including a copy of the unmodified license file (which the license itself appears to require) as LICENSE and a separate NOTICE file with your copyright statement (again as suggested by the license).

No worries if there are reasons not to do this, I just thought it would be okay to ask politely.

**Comment by cowtowncoder** [comment]
@ajorg-aws reasonable question, and I think this:

https://github.com/FasterXML/jackson-annotations/pull/178

would be a step towards better interoperability?

**Comment by ajorg-aws** [comment]
Looks like it should, yes. Thank you!
