### ISSUE TITLE
Missing LICENSE file for jackson-datatypes-collections/guava

### ISSUE THREAD

**Issue by emanuelbulic** [FasterXML/jackson-datatypes-collections#82]
I can find the LICENSE files for pcollections and hppc, but not guava. I can find one in the deprecated repo:

https://github.com/FasterXML/jackson-datatype-guava/blob/master/src/main/resources/META-INF/LICENSE

**Comment by cowtowncoder** [comment]
Oh. That is odd -- thank you for reporting this!

**Comment by cowtowncoder** [comment]
Added LICENSE for guava module, as well as eclipse-collections (which was also missing).
