### ISSUE TITLE
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.AnnotationIntrospector.findPropertyIgnoralByName

### ISSUE THREAD

**Issue by linjunhao1997** [FasterXML/jackson-datatypes-collections#84]
happen in 2.12.1.  My Spring Boot version is 2.2.5.RELEASE. But 2.11.4 is available

**Comment by cowtowncoder** [comment]
Sounds like a version conflict within your deployment: something has been compiled to expect `jackson-databind` 2.12 (which introduced this method), but has an older version.
As the general rule, the minor version of all Jackson components should match: in this case you likely have an older version of `jackson-databind` but newer (2.12.x) of some module (like `jackson-module-kotlin`, maybe).
