### ISSUE TITLE
Eclipse Collection serialization for Pairs does not work when upgrading to EC version 11.0.0

### ISSUE THREAD

**Issue by goldbal330** [FasterXML/jackson-datatypes-collections#94]
Pair interface had new default methods added in 11.0.0 (isEqual() and isSame()).
This seems to be breaking Jackson serialization.
The errors can be reproduced by upgrading the version of EC in Jackson-datatypes-collections to 11.0.0.

The following jUnit tests fail:
[ERROR] Failures: 
[ERROR]   DeserializerTest.primitivePairs:659 expected:<{"one":"a","two":"i"[]}> but was:<{"one":"a","two":"i"[,"equal":false,"same":false]}>
[ERROR]   DeserializerTest.triple:707 expected:<{"one":"a","two":2,"three":false}> but was:<{"equal":false,"three":false,"same":false,"one":"a","two":2}>
[ERROR]   DeserializerTest.triplet:721 expected:<{"one":"a","two":"b","three":"c"}> but was:<{"equal":false,"three":"c","same":false,"one":"a","two":"b"}>
[ERROR]   DeserializerTest.twin:673 expected:<{"one":"q","two":"d"[]}> but was:<{"one":"q","two":"d"[,"equal":false,"same":false]}>

**Comment by yawkat** [comment]
Thanks for the report.

I will try to fix this next week, hopefully my CLA will go through by then.

**Comment by cowtowncoder** [comment]
@yawkat If you refer to fasterxml CLA, we already have one from 2020.

**Comment by cowtowncoder** [comment]
Fix will be in 2.13.4 / 2.14.0.
